### ISSUE TITLE
Fails to build on Gentoo

### ISSUE THREAD

**Issue by jimbair** [cloudkick/cloudkick-config#1]
Greetings. When trying to build this package using scons, you get the following error:

```
scons: Reading SConscript files ...
Checking for C function floor()... (cached) no
Checking /usr/bin/curl-config --prefix ....(cached)  /usr
Checking /usr/bin/curl-config --libs ....(cached)  -lcurl -lssl -lcrypto -lrt -lssl -lcrypto -lz
Checking whether __i386__ is declared... (cached) no
Checking whether __amd64__ is declared... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
gcc -o src/ckc.o -c -Wall -g -O0 -I/usr/include src/ckc.c
In file included from src/ckc.c:17:0:
src/ckc.h:26:24: fatal error: curl/types.h: No such file or directory
compilation terminated.
scons: *** [src/ckc.o] Error 1
scons: building terminated because of errors.
```

It appears an update to curl has broken the build. Running the latest, stable x86_64 Gentoo - can provide more info as needed.

Thanks!

**Comment by cwgem** [comment]
This is because curl/types.h was removed by upstream for deprecation purposes:

http://curl.haxx.se/mail/tracker-2011-07/0011.html

If you simply remove the include from src/ckc.h it compiles just fine.

**Comment by jimbair** [comment]
Thanks for the heads up. Made the change and built on my Gentoo cloud server and confirmed working. Put in the following pull request: https://github.com/cloudkick/cloudkick-config/pull/2

**Comment by jimbair** [comment]
This appears to have been merged - just waiting for an updated ebuild via the Gentoo overlay. =)

**Comment by jimbair** [comment]
Closing as this was obviously never implemented. :)
